name: 'Run tests'
on:
  push:
    branches:
      - main

jobs:
  run:
    strategy:
      fail-fast: true
      matrix:
        hostname:
          - "https://aaronbatilo.dev"
          - "https://mentallyanimated.com"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute test
        uses: grafana/k6-action@v0.3.0
        env:
          HOSTNAME: ${{ matrix.hostname }}
        with:
          filename: main.js

      - run: |
          name="$(echo '${{ matrix.hostname }}' | sed 's/[^a-zA-Z0-9]/_/g')"
          cat ${name}.html
