name: 'Run tests'
on:
  push:
    branches:
      - main

jobs:
  list-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.targets.outputs.targets }}
    steps:
      - id: targets
        run: |
          targets="
          https://aaronbatilo.dev
          https://mentallyanimated.com
          "
          targets_json="$(echo "${targets}" | jq -Rs '{targets: split("\n") | map(select(. != ""))}')"
          echo "targets_json=${targets_json}" >> "$GITHUB_OUTPUT"
  run:
    needs: [list-targets]
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.list-targets.outputs.targets) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute test
        uses: grafana/k6-action@v0.3.0
        env:
          HOSTNAME: ${{ matrix.hostname }}
        with:
          filename: main.js

      - run: |
          name="$(echo '${{ matrix.hostname }}' | sed 's/[^a-zA-Z0-9]/_/g')"
          cat ${name}.html
