name: 'Run tests'
on:
  push:
    branches:
      - main

jobs:
  list-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.targets.outputs.targets }}
    steps:
      - id: targets
        run: |
          targets="
          https://aaronbatilo.dev
          https://mentallyanimated.com
          "
          # Convert the multiline string into a JSON array
          json_array=$(echo "$targets" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          # Create a JSON object with the key "targets"
          json_object=$(jq -n --argjson arr "$json_array" '{"targets": $arr}')

          echo "targets=${json_object}" >> "$GITHUB_OUTPUT"
  run:
    needs: [list-targets]
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.list-targets.outputs.targets) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute test
        uses: grafana/k6-action@v0.3.0
        env:
          HOSTNAME: ${{ matrix.hostname }}
        with:
          filename: main.js

      - run: |
          name="$(echo '${{ matrix.hostname }}' | sed 's/[^a-zA-Z0-9]/_/g')"
          cat ${name}.html
